// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
  Bindings: {
    TURSO_CONNECTION_URL: string,
    TURSO_AUTH_TOKEN: string
  }
}
